openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple API
  description: A simple API to illustrate OpenAPI concepts

servers:
  - url: https://example.io/v1


tags:
  - name: users
    description: Routes related to users

paths:
  /user:
    post:
      description: Creates a user
      #  ---- /Added lines  ----------------------------------------  
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/plain:
            schema:
              type: string
      tags:
      - users
      responses:
        '200':
          description: Successful creation of the user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
components:
  schemas:
    User:
      title: Component containing a user  
      type: object
      properties:
        name:
          type: string
          description: Message text
        email:
          type: string
          description: Email of the user
        password:
          type: string
          description: Chosen password of the user
      required:
        - name
        - email
        - password
      